// svelte/src/lib/pages/tic_tac_toe/TTTCell.svelte
<script>
  import { cls } from '../../util';
  import { createEventDispatcher } from 'svelte';

  export let letter = '';

  const emit = createEventDispatcher();

  const onClick = () => {
    if (!letter) {
      emit('select');
    }
  };

  $: classes = cls({ 'ttt-cell': true, empty: !letter });
</script>

<div class={classes} on:click={onClick}>
  {letter || ''}
</div>

<style>
  .ttt-cell {
    width: 100%;
    height: 100%;
    font-weight: bold;
    border: 1px solid black;
  }

  .ttt-cell.empty:hover {
    cursor: pointer;
    background-color: #ff3e00;
  }
</style>

// vue3/src/components/pages/tic_tac_toe/TTTCell.vue
<template>
  <div class="ttt-cell" :class="{ empty: !props.letter }" @click="onClick()">
    {{ letter }}
  </div>
</template>

<script setup>
const props = defineProps({
  letter: String,
});

const emit = defineEmits(['select']);

const onClick = () => emit('select');
</script>

<style>
.ttt-cell {
  width: 100%;
  height: 100%;
  font-weight: bold;
  border: 1px solid black;
}

.ttt-cell.empty:hover {
  cursor: pointer;
  background-color: #3fb27f;
}
</style>
