// angular/src/app/pages/tic-tac-toe-page/tic-tac-toe-page.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { Board } from 'src/app/code/types';
import { calculateWinner } from 'src/app/code/ttt';

function defaultBoard() {
  return { player: 'O', cells: Array(9).fill(null) };
}

@Component({
  selector: 'tic-tac-toe-page',
  templateUrl: './tic-tac-toe-page.component.html',
  styleUrls: ['./tic-tac-toe-page.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class TicTacToePageComponent {
  private _history: Board[] = [defaultBoard()];

  active: Board;
  winningPlayer: string | null = null;

  get history() {
    return this._history;
  }

  set history(value: Board[]) {
    this._history = value;
    this.update();
  }

  constructor() {
    this.active = this._history[this._history.length - 1];
  }

  update() {
    this.active = this._history[this._history.length - 1];
    this.winningPlayer = calculateWinner(this.active.cells);
  }

  onReset() {
    this.history = [defaultBoard()];
  }

  onUndo() {
    this.history.splice(-1, 1);
    this.update();
  }

  onChange(board: Board) {
    if (this.winningPlayer) {
      return;
    }

    this.history.push(board);
    this.update();
  }
}

<div class="tic-tac-toe-page">
  <div class="actions">
    <button (click)="onReset()">Reset</button>
    <button *ngIf="history.length > 1" (click)="onUndo()">Undo</button>
  </div>
  <div class="game-wrapper">
    <div class="game-area">
      <ttt-board
        [ngClass]="{ complete: !!winningPlayer }"
        [player]="active.player"
        [cells]="active.cells"
        (change)="onChange($event)"
      ></ttt-board>
      <div *ngIf="winningPlayer" class="winner">
        <div class="label">Player {{ winningPlayer }} Wins!</div>
      </div>
    </div>
  </div>
</div>

// react/src/components/pages/tic_tac_toe/TicTacToePage.js
import React from 'react';
import './TicTacToePage.css';

import TTTBoard from './TTTBoard';

import { calculateWinner } from '../../../code/ttt';
import clsx from 'clsx';

function initBoard() {
  return { player: 'O', cells: Array(9).fill(null) };
}

class TicTacToePage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      history: [initBoard()],
    };
  }

  onReset() {
    this.setState({ history: [initBoard()] });
  }

  onUndo() {
    const history = this.state.history.slice();
    history.splice(-1, 1);
    this.setState({ history });
  }

  onChange(event) {
    const active = this.state.history[this.state.history.length - 1];
    const winner = calculateWinner(active.cells);
    if (winner) {
      return;
    }
    const history = this.state.history.slice();
    history.push(event);
    this.setState({ history });
  }

  render() {
    const active = this.state.history[this.state.history.length - 1];

    const winningPlayer = calculateWinner(active.cells);

    if (this.state.history.length > 1) {
      var undo = <button onClick={() => this.onUndo()}>Undo</button>;
    }

    if (winningPlayer) {
      var winner = (
        <div className="winner">
          <div className="label">Player {winningPlayer} Wins!</div>
        </div>
      );
    }

    return (
      <div className="tic-tac-toe-page">
        <div className="actions">
          <button onClick={() => this.onReset()}>Reset</button>
          {undo}
        </div>
        <div className="game-wrapper">
          <div className="game-area">
            <TTTBoard
              className={clsx({ complete: !!winningPlayer })}
              player={active.player}
              cells={active.cells}
              onChange={e => this.onChange(e)}
            />
            {winner}
          </div>
        </div>
      </div>
    );
  }
}

export default TicTacToePage;
