// svelte/src/lib/pages/todo/TodoPage.svelte
<script>
  import TodoCard from './TodoCard.svelte';

  let todos = [{ title: 'Example todo', created: new Date(), completed: null }];

  function setTodos(data) {
    todos = data.slice();
  }

  const onAdd = () => {
    const entries = todos.slice();
    const entry = { title: '', created: new Date(), completed: null };
    entries.push(entry);
    setTodos(entries);
  };

  const onToggleComplete = index => {
    const entries = todos.slice();
    const newEntry = { ...entries[index] };

    if (newEntry.completed) {
      newEntry.completed = null;
    } else {
      newEntry.completed = new Date();
    }

    entries[index] = newEntry;

    setTodos(entries);
  };

  const onTextChange = (index, title) => {
    console.dir(title);
    const entries = todos.slice();
    const newEntry = { ...entries[index], title };

    entries[index] = newEntry;

    setTodos(entries);
  };

  const onDelete = index => {
    const entries = todos.slice();
    entries.splice(index, 1);
    setTodos(entries);
  };
</script>

<div class="todo-page">
  <div class="add">
    <button on:click={onAdd}>Create New</button>
  </div>
  <div class="cards">
    {#each todos as todo, index}
      <TodoCard
        title={todo.title}
        completed={todo.completed}
        on:toggle={() => onToggleComplete(index)}
        on:textChange={e => onTextChange(index, e.detail)}
        on:delete={() => onDelete(index)}
      />
    {/each}
  </div>
</div>

<style>
  .todo-page .cards {
    min-height: 4rem;
    display: flex;
    flex-wrap: wrap;
  }

  .todo-page .cards .todo-card.dim {
    opacity: 0.5;
  }
</style>

// vue3/src/components/pages/todo/TodoPage.vue
<template>
  <div class="todo-page">
    <div class="add">
      <button @click="onAdd()">Create New</button>
    </div>
    <div class="cards">
      <TodoCard
        v-for="(entry, index) in todos"
        :class="{ dim: !!entry.completed }"
        :key="index"
        v-bind="entry"
        @toggle="onToggleComplete(index)"
        @textChange="onTextChange(index, $event)"
        @delete="onDelete(index)"
      />
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useStore } from 'vuex';
import TodoCard from './TodoCard.vue';

const store = useStore();

const todos = computed(() => store.state.todos);

const setTodos = todos => store.commit('setTodos', todos);

const onAdd = () => {
  const entries = todos.value.slice();
  const entry = { title: '', created: new Date(), completed: null };
  entries.push(entry);
  setTodos(entries);
};

const onToggleComplete = index => {
  const entries = todos.value.slice();
  const newEntry = { ...entries[index] };

  if (newEntry.completed) {
    newEntry.completed = null;
  } else {
    newEntry.completed = new Date();
  }

  entries[index] = newEntry;

  setTodos(entries);
};

const onTextChange = (index, title) => {
  const entries = todos.value.slice();
  const newEntry = { ...entries[index], title };
  entries[index] = newEntry;
  setTodos(entries);
};

const onDelete = index => {
  const entries = todos.value.slice();
  entries.splice(index, 1);
  setTodos(entries);
};
</script>

<style>
.todo-page .cards {
  min-height: 4rem;
  display: flex;
  flex-wrap: wrap;
}

.todo-page .cards .todo-card.dim {
  opacity: 0.5;
}
</style>
