// angular/src/app/layout/nav-item/nav-item.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { CustomRoute } from 'src/app/code/types';

@Component({
  selector: 'nav-item',
  templateUrl: './nav-item.component.html',
  styleUrls: ['./nav-item.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class NavItemComponent {
  @Input() route: CustomRoute | undefined = undefined;
}

<div class="nav-item">
  <icon [icon]="route?.icon || ''"></icon>
  <span class="nav-bar-tooltip">{{ route?.name }}</span>
</div>

// react/src/components/layout/NavItem.js
import React from 'react';
import './NavItem.css';

import Icon from '../../components/Icon';

class NavItem extends React.Component {
  render() {
    const route = this.props.route;
    return (
      <div className="nav-item">
        <Icon icon={route.icon} />
        <span className="nav-bar-tooltip">{route.name}</span>
      </div>
    );
  }
}

export default NavItem;
