// solidjs/src/index.jsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Router, hashIntegration } from "solid-app-router";
import App from "./App";

render(
  () => (
    <Router source={hashIntegration()}>
      <div>This is some stuff</div>
      <App />
    </Router>
  ),
  document.getElementById("root")
);

// react/src/index.js
import React from 'react';
import { render } from 'react-dom';

import { Provider } from 'react-redux';
import store from './store/store';

import App from './App';

render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root'),
);
