// svelte/src/lib/pages/todo/TodoPage.svelte
<script>
  import TodoCard from './TodoCard.svelte';

  let todos = [{ title: 'Example todo', created: new Date(), completed: null }];

  function setTodos(data) {
    todos = data.slice();
  }

  const onAdd = () => {
    const entries = todos.slice();
    const entry = { title: '', created: new Date(), completed: null };
    entries.push(entry);
    setTodos(entries);
  };

  const onToggleComplete = index => {
    const entries = todos.slice();
    const newEntry = { ...entries[index] };

    if (newEntry.completed) {
      newEntry.completed = null;
    } else {
      newEntry.completed = new Date();
    }

    entries[index] = newEntry;

    setTodos(entries);
  };

  const onTextChange = (index, title) => {
    console.dir(title);
    const entries = todos.slice();
    const newEntry = { ...entries[index], title };

    entries[index] = newEntry;

    setTodos(entries);
  };

  const onDelete = index => {
    const entries = todos.slice();
    entries.splice(index, 1);
    setTodos(entries);
  };
</script>

<div class="todo-page">
  <div class="add">
    <button on:click={onAdd}>Create New</button>
  </div>
  <div class="cards">
    {#each todos as todo, index}
      <TodoCard
        title={todo.title}
        completed={todo.completed}
        on:toggle={() => onToggleComplete(index)}
        on:textChange={e => onTextChange(index, e.detail)}
        on:delete={() => onDelete(index)}
      />
    {/each}
  </div>
</div>

<style>
  .todo-page .cards {
    min-height: 4rem;
    display: flex;
    flex-wrap: wrap;
  }

  .todo-page .cards .todo-card.dim {
    opacity: 0.5;
  }
</style>

// vue2/src/components/pages/todo/TodoPage.vue
<template>
  <div class="todo-page">
    <div class="add">
      <button @click="onAdd()">Create New</button>
    </div>
    <div class="cards">
      <TodoCard
        v-for="(entry, index) in entries"
        :class="{ dim: !!entry.completed }"
        :key="index"
        v-bind="entry"
        @toggle="onToggleComplete(entry)"
        @textChange="onTextChange(entry, $event)"
        @delete="onDelete(index)"
      />
    </div>
  </div>
</template>

<script>
import TodoCard from './TodoCard.vue';

export default {
  name: 'TodoPage',
  components: {
    TodoCard,
  },
  data: () => {
    return {
      entries: [{ title: 'Example item', created: new Date(), completed: null }],
    };
  },
  methods: {
    onAdd() {
      const entry = { title: '', created: new Date(), completed: null };
      this.entries.push(entry);
    },
    onToggleComplete(entry) {
      if (entry.completed) {
        entry.completed = null;
      } else {
        entry.completed = new Date();
      }

      this.entries = this.entries.slice();
    },
    onTextChange(entry, title) {
      entry.title = title;
      this.entries = this.entries.slice();
    },
    onDelete(index) {
      this.entries.splice(index, 1);
      this.entries = this.entries.slice();
    },
  },
};
</script>

.<style>
.todo-page .cards {
  min-height: 4rem;
  display: flex;
  flex-wrap: wrap;
}

.todo-page .cards .todo-card.dim {
  opacity: 0.5;
}
</style>
