// vue2/src/components/pages/tic_tac_toe/TTTBoard.vue
<template>
  <div class="ttt-board">
    <TTTCell
      v-for="(letter, index) in cells"
      :key="index"
      :letter="letter"
      @select="onSelect(index)"
    />
  </div>
</template>

<script>
import TTTCell from './TTTCell.vue';

function nextPlayer(player) {
  if (player === 'X') {
    return 'O';
  }
  return 'X';
}

export default {
  name: 'TTTBoard',
  components: {
    TTTCell,
  },
  props: {
    player: { type: String, required: true },
    cells: { type: Array, required: true },
  },
  methods: {
    onSelect(index) {
      this.setCell(index);
    },
    setCell(index) {
      const player = nextPlayer(this.player);
      const cells = this.cells.slice();
      cells[index] = player;

      const state = {
        player,
        cells,
      };

      this.$emit('change', state);
    },
  },
};
</script>

<style>
.ttt-board {
  display: grid;
  grid-template-columns: 4rem 4rem 4rem;
}

.ttt-board .ttt-cell {
  aspect-ratio: 1;
  font-size: 2.5rem;
  text-align: center;
  height: 4rem;
  width: 4rem;
  line-height: 4rem;
}
</style>

// svelte/src/lib/pages/tic_tac_toe/TTTBoard.svelte
<script>
  import { cls } from '../../util';
  import { createEventDispatcher } from 'svelte';
  import TTTCell from './TTTCell.svelte';

  let className = '';

  export let player = '';
  export let cells = [];
  export { className as class };

  const emit = createEventDispatcher();

  function getNextPlayer(p) {
    return p === 'X' ? 'O' : 'X';
  }

  function setCell(index) {
    const newPlayer = getNextPlayer(player);
    const newCells = cells.slice();
    newCells[index] = newPlayer;

    const state = { player: newPlayer, cells: newCells };

    emit('change', state);
  }

  const onSelect = index => setCell(index);

  $: classes = cls({ 'ttt-board': true, [className]: true });
</script>

<div class={classes}>
  {#each cells as letter, index}
    <TTTCell {letter} on:select={() => onSelect(index)} />
  {/each}
</div>

<style>
  .ttt-board {
    display: grid;
    grid-template-columns: 4rem 4rem 4rem;
  }

  .ttt-board :global(.ttt-cell) {
    aspect-ratio: 1;
    font-size: 2.5rem;
    text-align: center;
    height: 4rem;
    width: 4rem;
    line-height: 4rem;
  }
</style>
