// angular/src/app/pages/todo/card/todo-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'todo-card',
  templateUrl: './todo-card.component.html',
  styleUrls: ['./todo-card.component.css'],
})
export class TodoCardComponent {
  @Input() childMessage: string = '';
}

<div class="todo-card">
  <complete-icon
    [value]="!!completed"
    (input)="onToggleCompleted($event)"
  ></complete-icon>
  <input
    class="title"
    [value]="title"
    [disabled]="!!completed"
    (change)="onTextChange($event)"
  />
  <icon [icon]="'circle-check'"></icon>
</div>

// react/src/components/pages/todo/TodoCard.js
import React from 'react';
import './TodoCard.css';

import Icon from '../../Icon';

class TodoCard extends React.Component {
  render() {
    const { title, completed } = this.props;

    return (
      <div class="todo-card">
        {/* <CompleteIcon value={!!completed} onInput={e => this.props.onToggleCompleted(e)} /> */}
        <input
          className={title}
          value={title}
          disabled={!!completed}
          onChange={e => this.props.onTextChange(e.target.value)}
        />
        <Icon className="delete" icon="xmark" onClick={this.props.onDelete} />
      </div>
    );
  }
}

export default TodoCard;
