// vue3/src/components/layout/Layout.vue
<template>
  <div class="layout">
    <div class="nav-bar">
      <img src="logo.png" />
      <router-link v-for="route in routes" :key="route.path" :to="route.path">
        <NavItem :name="route.name" :icon="route.meta.icon" />
      </router-link>
    </div>

    <div class="page-wrapper">
      <div class="page">
        <router-view />
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import NavItem from './NavItem.vue';

import router from '@/code/router';

const routes = computed(() => router.getRoutes().filter(r => !r.meta.hide));
</script>

<style>
body {
  margin: 0;
}

.layout {
  color: black;
}

.layout .nav-bar {
  position: fixed;
  top: 0;
  display: flex;
  flex-direction: column;
  width: 4rem;
  background-color: #202225;
  height: 100vh;
  z-index: 1000;
}

.layout .nav-bar img {
  border-bottom: 1px solid gray;
  padding: 0.5rem;
}

.layout .page-wrapper {
  margin-left: 4rem;
}

.layout .page {
  margin: 1rem;
  padding-top: 1rem;
  padding-bottom: 1.5rem;
  border-bottom: 0.1px solid gray;
}
</style>

// svelte/src/lib/layout/Layout.svelte
<script>
  import { Router, Route, Link } from 'svelte-navigator';

  import logo from '../../assets/logo.png';
  import NavItem from './NavItem.svelte';

  export let routes = [];

  $: validRoutes = routes.filter(r => (r.meta || {}).hide !== true);
</script>

<Router>
  <div class="layout">
    <nav class="eggplant">
      <img src={logo} alt="Svelte Logo" />
      {#each validRoutes as route}
        <Link to={route.path}>
          <NavItem {route} />
        </Link>
      {/each}
    </nav>

    <div class="page-wrapper">
      <div class="page">
        {#each routes as route}
          <Route path={route.path}>
            <svelte:component this={route.component} />
          </Route>
        {/each}
      </div>
    </div>
  </div>
</Router>

<style>
  .layout {
    color: black;
  }

  .layout nav {
    position: fixed;
    top: 0;
    display: flex;
    flex-direction: column;
    width: 4rem;
    background-color: #202225;
    height: 100vh;
    z-index: 1000;
  }

  .layout nav img {
    border-bottom: 1px solid gray;
    padding: 0.5rem;
  }

  .layout .page-wrapper {
    margin-left: 4rem;
  }

  .layout .page {
    margin: 1rem;
    padding-top: 1rem;
    padding-bottom: 1.5rem;
    border-bottom: 0.1px solid gray;
  }
</style>
