// svelte/src/App.svelte
<script>
  import { Router, Link, Route } from 'svelte-navigator';
  import routes from './lib/routes';
  import TodoPage from './lib/pages/todo/TodoPage.svelte';
  import TicTacToePage from './lib/pages/tic_tac_toe/TicTacToePage.svelte';
</script>

<Router>
  <nav>
    <Link to="/">Home</Link>
    <Link to="todo">Todo</Link>
    <Link to="tic_tac_toe">Tic Tac Toe</Link>
  </nav>

  <div>
    <Route path="/" component={TodoPage} />
    <Route path="todo" component={TodoPage} />
    <Route path="tic_tac_toe" component={TicTacToePage} />
  </div>
</Router>

// solidjs/src/App.jsx
import { Routes, Route, Link } from "solid-app-router";

import TodoPage from "./pages/TodoPage";
import TicTacToePage from "./pages/TicTacToePage";

export default function App() {
  return (
    <div>
      <h1>My Site with Lots of Pages</h1>
      <nav>
        <Link href="/todo">Todo</Link>
        <Link href="/tic_tac_toe">Tic-Tac-Toe</Link>
      </nav>
      <Routes>
        <Route path="/todo" element={<TodoPage />} />
        <Route path="/tic_tac_toe" element={<TicTacToePage />} />
      </Routes>
    </div>
  );
}
