// angular/src/app/pages/todo-page/card/todo-card.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewEncapsulation,
} from '@angular/core';

@Component({
  selector: 'todo-card',
  templateUrl: './todo-card.component.html',
  styleUrls: ['./todo-card.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class TodoCardComponent {
  @Input() title: string = '';
  @Input() completed: Date | null | undefined = undefined;

  @Output() toggle = new EventEmitter<boolean>();
  @Output() textChange = new EventEmitter<string>();
  @Output() delete = new EventEmitter();

  onToggleCompleted(bool: boolean) {
    this.toggle.emit(bool);
  }

  onTextChange(event: any) {
    this.textChange.emit(event.target.value);
  }

  onDelete() {
    this.delete.emit();
  }
}

<div class="todo-card">
  <complete-icon
    [value]="!!completed"
    (input)="onToggleCompleted($event)"
  ></complete-icon>
  <input
    class="title"
    [value]="title"
    [disabled]="!!completed"
    (change)="onTextChange($event)"
  />
  <icon class="delete" icon="xmark" (click)="onDelete()"></icon>
</div>

// solidjs/src/pages/todo/TodoCard.jsx
import './TodoCard.css';
import Icon from '../../components/Icon';
import CompleteIcon from './CompleteIcon';

export default props => {
  return (
    <div className="todo-card">
      <CompleteIcon value={!!props.completed} onToggle={bool => props.onToggle?.(bool)} />
      <input
        className="title"
        value={props.title}
        disabled={!!props.completed}
        onChange={e => props.onTextChange?.(e.target.value)}
      />
      <Icon className="delete" icon="xmark" onClick={() => props.onDelete?.()} />
    </div>
  );
};
