// react/src/components/pages/todo/TodoCard.js
import React from 'react';
import './TodoCard.css';

import Icon from '../../Icon';

class TodoCard extends React.Component {
  render() {
    const { title, completed } = this.props;

    return (
      <div class="todo-card">
        {/* <CompleteIcon value={!!completed} onInput={e => this.props.onToggleCompleted(e)} /> */}
        <input
          className={title}
          value={title}
          disabled={!!completed}
          onChange={e => this.props.onTextChange(e.target.value)}
        />
        <Icon className="delete" icon="xmark" onClick={this.props.onDelete} />
      </div>
    );
  }
}

export default TodoCard;

// angular/src/app/pages/todo-page/card/todo-card.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewEncapsulation,
} from '@angular/core';

@Component({
  selector: 'todo-card',
  templateUrl: './todo-card.component.html',
  styleUrls: ['./todo-card.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class TodoCardComponent {
  @Input() title: string = '';
  @Input() completed: Date | null | undefined = undefined;

  @Output() toggle = new EventEmitter<boolean>();
  @Output() textChange = new EventEmitter<string>();
  @Output() delete = new EventEmitter();

  onToggleCompleted(bool: boolean) {
    this.toggle.emit(bool);
  }

  onTextChange(event: any) {
    this.textChange.emit(event.target.value);
  }

  onDelete() {
    this.delete.emit();
  }
}

<div class="todo-card">
  <complete-icon
    [value]="!!completed"
    (input)="onToggleCompleted($event)"
  ></complete-icon>
  <input
    class="title"
    [value]="title"
    [disabled]="!!completed"
    (change)="onTextChange($event)"
  />
  <icon class="delete" icon="xmark" (click)="onDelete()"></icon>
</div>
